name: Publish Docker Image

on:
  release:
    types: [published]
    paths:
      - "apps/server/**"
      - ".github/workflows/publish-docker-image.yaml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: cd into server
        run: cd apps/server
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          # add the release tag to the image as well as the latest tag
          tags: kcoderhtml/scaffold-server:latest, kcoderhtml/scaffold-server:${{ github.event.release.tag_name }}
